apiVersion: apps/v1
kind: Deployment
metadata:
  name: filmcast-deployment
  labels:
    app: filmcast
spec:
  replicas: 3
  selector:
    matchLabels:
      app: filmcast
  template:
    metadata:
      labels:
        app: filmcast
    spec:
      containers:
      - name: filmcast
        image: dataquaint/filmcast
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: filmcast-service
spec:
  type: LoadBalancer
  selector:
    app: filmcast
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
