---
apiVersion: v1
kind: Service
metadata:
  name: filmcast-service
  namespace: filmcast-app  # ‚Üê Add namespace here
spec:
  type: LoadBalancer
  selector:
    app: filmcast
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
